name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'sample/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'sample/**'

jobs:
  build:
    # Skip workflow if commit message contains [skip ci]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/*.apk
