name: Android CI

on:
  release:
    types: [ published ]
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'sample/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'sample/**'

jobs:
  build:
    # Skip workflow if commit message contains [skip ci]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Debug APK
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: ./gradlew clean :app:assembleDebug --stacktrace
        
      - name: Build Release APK
        if: github.event_name == 'release'
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 -d > app/candybar.jks
          ./gradlew clean :app:assembleRelease --stacktrace
          
      - name: Upload Debug APK
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/*.apk
          
      - name: Upload Release APK
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: app/build/outputs/apk/release/*.apk
